baseURL = "http://djaus2.github.io/"
languageCode = "en-us"
title = "Computing Thoughts"
theme = "hugo-nuo"
publishDir = "docs"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "About"
  weight = 20
  identifier = "about"
  url = "http://www.mindviewinc.com/About/Bruce.php"

[[menu.main]]
  name = "Embedded01.com"
  weight = 20
  identifier = "embedded101"
  url = "http://embedded101.com"

[[menu.main]]
  name = "Atomic Scala"
  weight = 20
  identifier = "atomicscala"
  url = "http://www.atomicscala.com/"

[[menu.main]]
  name = "Winter Tech Forum"
  weight = 20
  identifier = "wintertechforum"
  url = "http://www.wintertechforum.com/"

# Add your own params here
[params]
  author = "David Jones"
  avatar = "/img/BruceEckelPicture.png"
  seotitle = "Hugo Blog (SEO Version)"
  subtitle = "David Jones' Programming Blog"
  description = "A blog about all the things related to programming by David Jones.
  paginate = 10
  email = "davidjones@sportronics.com.au"
  github = "djaus2"
  twitter = "cedriverwiz"
